// Agent timeline data — the "chain" of tool calls + reasoning the agent performs
// while building an app. Each entry is either a "tool" call or a "thought" (reasoning).

const AGENT_TIMELINE = [
  {
    id: 1,
    kind: "thought",
    text: "Let me break this down. The user wants a fitness tracker with social features. I'll start by scaffolding the project and setting up the data model.",
    duration: 1800,
  },
  {
    id: 2,
    kind: "tool",
    tool: "create_project",
    icon: "folder",
    title: "Scaffolding project",
    subtitle: "fittrack-social",
    detail: "react · typescript · expo",
    duration: 1400,
    artifact: {
      type: "tree",
      lines: [
        "fittrack-social/",
        "├─ app/",
        "│  ├─ (tabs)/",
        "│  └─ _layout.tsx",
        "├─ components/",
        "└─ package.json",
      ],
    },
  },
  {
    id: 3,
    kind: "tool",
    tool: "search_docs",
    icon: "search",
    title: "Searching Expo docs",
    subtitle: "HealthKit integration",
    detail: "3 results found",
    duration: 1200,
  },
  {
    id: 4,
    kind: "thought",
    text: "Found it — `expo-health` exposes step counts and workout sessions. I'll wire it into a hook that streams updates so the UI feels live.",
    duration: 2200,
  },
  {
    id: 5,
    kind: "tool",
    tool: "write_file",
    icon: "code",
    title: "Writing useHealthData.ts",
    subtitle: "hooks/useHealthData.ts",
    detail: "+ 64 lines",
    duration: 1600,
    artifact: {
      type: "code",
      lang: "ts",
      lines: [
        "export function useHealthData() {",
        "  const [steps, setSteps] = useState(0);",
        "  useEffect(() => {",
        "    const sub = Health.subscribe(setSteps);",
        "    return () => sub.remove();",
        "  }, []);",
        "  return { steps };",
        "}",
      ],
    },
  },
  {
    id: 6,
    kind: "tool",
    tool: "write_file",
    icon: "code",
    title: "Building HomeScreen.tsx",
    subtitle: "app/(tabs)/index.tsx",
    detail: "+ 132 lines",
    duration: 1800,
  },
  {
    id: 7,
    kind: "thought",
    text: "The home screen needs a hero ring showing today's progress. I'll use Skia for the gradient stroke — it'll look way nicer than SVG.",
    duration: 1900,
  },
  {
    id: 8,
    kind: "tool",
    tool: "install",
    icon: "package",
    title: "Installing dependencies",
    subtitle: "@shopify/react-native-skia",
    detail: "1 package · 2.3s",
    duration: 1500,
  },
  {
    id: 9,
    kind: "tool",
    tool: "run",
    icon: "play",
    title: "Running build",
    subtitle: "expo start --ios",
    detail: "compiled in 4.1s",
    duration: 2000,
    status: "ok",
  },
  {
    id: 10,
    kind: "thought",
    text: "Build is green. Preview is live on the simulator. Want me to add the social feed next, or wire up auth first?",
    duration: 2000,
    final: true,
  },
];

window.AGENT_TIMELINE = AGENT_TIMELINE;
