#!/usr/bin/env bash
# Proxies filebrowser (port 9090) behind nginx at /files/
# Idempotent — safe to re-run.

SERVER_NAME="%%SERVER_NAME%%"   # e.g. apps-father.com or dev.apps-father.com
FB_BASEURL="/files"
FB_DB="/opt/filebrowser/filebrowser.db"
NGINX_SNIPPET="/etc/nginx/snippets/filebrowser-proxy.conf"
NGINX_SITE="%%NGINX_SITE%%"     # path to the nginx site config file

set -e

echo ""
echo "=== Filebrowser nginx proxy setup ==="
echo "  Server name : $SERVER_NAME"
echo "  Proxy path  : $FB_BASEURL/"
echo "  FB database : $FB_DB"
echo ""

# ── 1. Set filebrowser baseurl ─────────────────────────────────────────────
echo "--> Configuring filebrowser baseurl..."
if [ -f "$FB_DB" ]; then
  filebrowser -d "$FB_DB" config set --baseurl "$FB_BASEURL" 2>/dev/null || \
    echo "    (warning: could not set baseurl — may need manual config)"
  echo "    baseurl set to $FB_BASEURL"
else
  echo "    WARNING: $FB_DB not found, skipping baseurl config"
fi

# ── 2. Write nginx snippet ─────────────────────────────────────────────────
echo "--> Writing nginx snippet to $NGINX_SNIPPET..."
cat > "$NGINX_SNIPPET" << 'NGINX_EOF'
# Filebrowser proxy — generated by proxy-filebrowser.sh
location /files/ {
    proxy_pass         http://127.0.0.1:9090/files/;
    proxy_http_version 1.1;
    proxy_set_header   Host              $host;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   Upgrade           $http_upgrade;
    proxy_set_header   Connection        "upgrade";
    proxy_read_timeout 300s;
    proxy_buffering    off;
    client_max_body_size 500M;
}
NGINX_EOF
echo "    snippet written"

# ── 3. Include snippet in site config before the catch-all location / ───────
echo "--> Checking nginx site config: $NGINX_SITE..."
if [ -f "$NGINX_SITE" ]; then
  if grep -q "filebrowser-proxy.conf" "$NGINX_SITE"; then
    echo "    already included — skipping"
  else
    # Insert include on the line immediately before 'location /' so the more
    # specific /files/ prefix wins over the catch-all location / block.
    if grep -q "location /" "$NGINX_SITE"; then
      sed -i "s|^\(\s*location /\s*{\)$|    include snippets/filebrowser-proxy.conf;\n\1|" "$NGINX_SITE"
      # Fallback: if the above pattern didn't match (different formatting), use a simpler approach
      if ! grep -q "filebrowser-proxy.conf" "$NGINX_SITE"; then
        sed -i "/location \//i\\    include snippets/filebrowser-proxy.conf;" "$NGINX_SITE"
      fi
      echo "    include inserted before location / in $NGINX_SITE"
    else
      echo "    WARNING: could not find 'location /' in $NGINX_SITE"
      echo "    Add manually inside your server {} block (before location /):"
      echo "        include snippets/filebrowser-proxy.conf;"
    fi
  fi
else
  echo "    WARNING: $NGINX_SITE not found"
  echo "    Add this line manually inside your server {} block (before location /):"
  echo "        include snippets/filebrowser-proxy.conf;"
fi

# ── 4. Test and reload nginx ───────────────────────────────────────────────
echo "--> Testing nginx config..."
nginx -t
echo "--> Reloading nginx..."
systemctl reload nginx
echo "    nginx reloaded"

# ── 5. Restart filebrowser ─────────────────────────────────────────────────
echo "--> Restarting filebrowser..."
if systemctl is-active --quiet filebrowser 2>/dev/null; then
  systemctl restart filebrowser
  echo "    filebrowser restarted via systemctl"
elif pm2 list 2>/dev/null | grep -q filebrowser; then
  pm2 restart filebrowser
  echo "    filebrowser restarted via pm2"
else
  echo "    WARNING: could not detect filebrowser process manager"
  echo "    Restart filebrowser manually with: --baseurl /files flag"
fi

echo ""
echo "=== Done! Filebrowser is now available at: ==="
echo "    https://$SERVER_NAME/files/"
echo ""
echo "NOTE: If the UI looks broken after opening, hard-refresh (Ctrl+Shift+R)"
